name: Run Top 10 IT Companies Scraper

on:
  workflow_dispatch:

  schedule:
    # Runs every 6 hours in UTC time
    - cron: "0 */6 * * *"

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python Top10_IT_Companies_Scraper.py

      - name: Upload Excel output
        uses: actions/upload-artifact@v4
        with:
          name: Top_10_IT_Companies_Output
          path: Top_10_IT_Companies_India_Output.xlsx